version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cuistotfamily-db
    restart: always
    environment:
      POSTGRES_USER: cuistot
      POSTGRES_PASSWORD: cuistotpassword
      POSTGRES_DB: cuistotfamily
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
